name: CI

on:
  push:
    branches: [ test_workflow ]
  pull_request:
    branches: [ test_workflow ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: cd build && make
    - name: ctest
      run: cd build && ctest -V
